<div class="menu adm">
<ul>
	<li><a href="gestioncategorias.php"><span>gestion de categorias</span></a></li>
	<li><a href="cambiodeporcentaje.php"><span>cambio del porcentaje</span></a></li>
	<li><a href="historialdeventas.php"><span>ver historial de ventas</span></a></li>
	<li><a href="reporteproductos.php"><span>ver reportes de los productos</span></a></li>
	<li><a href="listadodeusuarios.php"><span>ver listado de usuarios</span></a></li>
	<li><a href="ventasconcretadas.php"><span>ver las ventas con sus ganancias</span></a></li>
</ul>
</div>