<?php require_once("/public/complementos/conexion.php");?>
<!doctype html>
<html lang="es">

	<head>
		<title></title>
		<meta http equiv="Content Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css" href="public/css/general.css">
		<link rel="stylesheet" type="text/css" href="public/css/categorias.css" />
        <script src="public/js/jquery-1.11.2.js"></script>
        <script src="public/js/busquedas.js" type="text/javascript"></script> 
        <script src="public/js/general.js" type="text/javascript"></script>
	</head>
<body>
		<header>
			<div class="cabecera">
				<a href="index.php" ><img class="logosubasta" src="pictures/sistema/bestnid.png"></a>
				<a href="index.php" ><img class="bestnid" src="pictures/sistema/bestnid logo.png"></a>
				<a href="contactenos.php" ><img class="contactoPublico" src="pictures/sistema/contactenos.png"></a>
				<a href="registrarse.php" ><img class="registrarse" src="pictures/sistema/registrarse.png"></a> 
				<a href="conectarse.php" ><img class="conectarse" src="pictures/sistema/conectarse.png"></a> 
				<a href="ayudaPublico.php" ><img class="ayuda" src="pictures/sistema/ayuda.png"></a> 
        	</div>
		</header>
	<section>
	<br><br><br><br><br><br>
	<div id="contenedor">