<div class="preguntasugerencia">
<span><h2>escriba su pregunta o sugerencia</h2></span><br>
<form action="controllers/contacto.php" method="POST">
	<input class="recuadro" type="text" name="reguntaconsulta" placeholder="titulo de su pregunta o sugerencia" required>
	<input class="recuadro" type="email" name="correo" placeholder="escriba su correo electronico" required>
	<textarea class="recuadro" name="contenido" type="text" placeholder="escriba su pregunta o sugerencia" required></textarea>
	<br>
	<input class="" type="submit" name="botonpreguntasujerencia" value="enviar" require>
</form>
</div>