 
 <div class="menu opciones">
        <ul>
         <li class='has-sub'><a href="ayudaUsuario.php"><span>donde nos llevan los menus</span></a></li>
         <li class='has-sub'><a href="ayudaModificarPerfil.php"><span>como modificar mi perfil</span></a></li>
         <li class='has-sub'><a href="ayudaRegistrarProducto.php"><span>como registrar un producto</span></a></li>
         <li class='has-sub'><a href="ayudaVerOfertasAMisProductos.php"><span>ver las ofertas a mis productos</span></a></li>
         <li class='has-sub'><a href="ayudaGestionarMisProductos.php"><span>gestionar mis productos</span></a></li>
         <li class='has-sub'><a href="ayudaGestionarMisOfertas.php"><span>como gestionar mis ofertas</span></a></li>
         <li class='has-sub'><a href="ayudaPagoAlGanar.php"><span>como pago por un producto ganado</span></a></li>
         <li class='has-sub'><a href="ayudaExplicacionTipoNotificaciones.php"><span>como saber que tipo notificaciones tengo</span></a></li>
         <li class='has-sub'><a href="ayudaElegirGanador.php"><span>como elegir un ganador</span></a></li>
         <li class='has-sub'><a href="ayudaContactarGanador.php"><span>como contactar a un ganador</span></a></li>
        </ul>   
 </div>