 
 <div class="menu opciones">
        <ul>
         <li class='has-sub'><a href="modificardatos.php"><span>modificar perfil</span></a></li>
         <li class='has-sub'><a href="registrarProductos.php"><span>registrar producto</span></a></li>
         <li class='has-sub'><a href="misOfertas.php"><span>ofertas a mis productos</span></a></li>
         <li class='has-sub'><a href="verMisProductosOfertados.php"><span>ver mis productos</span></a></li>
         <li class='has-sub'><a href="administrarMisOfertas.php"><span>mis ofertas</span></a></li>
         <li class='has-sub'><a href="confirmarOferta.php"><span>mis ofertas a confirmar</span></a></li>
         <li class='has-sub'><a href="verMisNotificaciones.php"><span>ver mis notificaciones</span></a></li>
        </ul>   
 </div>