 
 <div class="menu opciones">
        <ul>
         <li class='has-sub'><a href="ayudaPublico.php"><span>como regresar al inicio</span></a></li>
         <li class='has-sub'><a href="ayudaMenus.php"><span>donde nos llevan los menus</span></a></li>
         <li class='has-sub'><a href="ayudaRegistrarse.php"><span>como registrarse</span></a></li>
         <li class='has-sub'><a href="ayudapreguntaosugerencia.php"><span>hacer una pregunta o sugerencia</span></a></li>
         <li class='has-sub'><a href="ayudaconectarse.php"><span>como conectarse</span></a></li>
        </ul>   
 </div>